# Generated by Django 5.1.1 on 2024-09-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_photography_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='category',
            field=models.CharField(choices=[('MIXED', 'Mixed'), ('MAINECOON', 'Maine Coon')], default='', max_length=100),
        ),
    ]
