# Generated by Django 5.1.1 on 2024-09-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_photography_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='posted_by',
            field=models.CharField(default='Amanda', max_length=100),
            preserve_default=False,
        ),
    ]
