# Generated by Django 5.1.1 on 2024-09-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_photography_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='category',
            field=models.CharField(choices=[('MIXED', 'Mixed'), ('MOOONCOON', 'Moon Coon')], default='', max_length=100),
        ),
    ]
