# Generated by Django 5.1.1 on 2024-09-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_photography_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
